### 1. 책 검색
GET http://localhost:5000/book?id=1

### 2. 책 추가
POST http://localhost:5000/book
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="book"; filename="alice.epub"

< C:/Users/dlals/Downloads/alice.epub
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 3. 음악 검색
POST http://localhost:5000/music
Content-Type: application/json

{
    "cfi": "/6/6!/4/2[pgepubid00003]/4",
    "emotion": {"joy": 0.2, "excitement": 0.5, "gratitude": 0.7},
    "color": "#0066AA",
    "weather": "rain"
}

### 4. 음악 재생
#GET http://localhost:5000/music?id=10 // 브라우저 실행

### 5. 음악 정보
GET http://localhost:5000/music_info?id=10