### 1. 책 검색
GET http://localhost:5000/book?id=identifier-example-0

### 2. 책 추가
POST http://localhost:5000/book?id=identifier-example-0
Content-Type: application/json

{
    "content" : "content-example-0"
}

### 3. 음악 검색
POST http://localhost:5000/music
Content-Type: application/json

{
    "start" : "0",
    "end" : "10",
    "emotion" : ["happy", "joy"],
    "color" : "red",
    "weather" : "rain"
}

### 4. 음악 재생
GET http://localhost:5000/music?id=1